AutoConnect: true
AutoTaskTimeOut: 10
ServerAddress: lyonvisual
ClearDataPerAnalysis: 1
RetainAnalysisPerClear: 1
AnalysisSleepDuration: 1
AnalysisEngine: ConditionTest
SearchSignalWhenConnect: true
AddSpikeAnalysisWhenSignalOnLine: true
SaveVisualizationWhenExperimentAnalysisDone: true
RegisteredEx: None
WhiteList: []
BlackList: []
VisualizerWidth: 400
VisualizerHeight: 380
PlotExportWidth: 1280
PlotExportHeight: 854
PlotExportDPI: 120
