AutoConnect: false
AutoConnectTimeOut: 10
ServerAddress: lyonlab-visual
ClearDataPerAnalysis: 1
AnalysisSystem: DotNet
AddSpikeAnalysisWhenSignalOnLine: true
SaveVisualizationWhenExperimentStop: true
VisualizerWidth: 400
VisualizerHeight: 380
PlotExportWidth: 1280
PlotExportHeight: 854
PlotExportDPI: 120
RetainAnalysisPerClear: 1
AnalysisSleepResolution: 2
